#!/bin/bash

DOCKER_IMAGE="py-lethal-builder"

# check if docker image exists
if [[ "$(docker images -q $DOCKER_IMAGE 2> /dev/null)" == "" ]]; then
    echo "Docker image not found. Building..."
    docker build -t $DOCKER_IMAGE .
fi

sudo rm -rf __pycache__ build dist && \
    docker run -it -v "$(pwd):/src/" $DOCKER_IMAGE "\
        pip install -r requirements.txt && \
        wine 'C:\Python37\Scripts\create-version-file' data/lethal-mod-installer-versionfile.yaml --outfile /tmp/lethal-mod-installer-versionfile && \
        pyinstaller lethal-mod-installer.py --version-file=/tmp/lethal-mod-installer-versionfile --clean -F --hidden-import=queue --hidden-import=winreg -i data/icon.ico && \
        cp settings.yaml dist" && \
    sudo chmod 666 dist/settings.yaml && \
    sudo chown -R $USER:$USER dist/
